Correct syntax error in build;

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -115,12 +115,12 @@ jobs:
 
       - name: Test - Server Started
         run: |
-          check_for_config() {
-            if ! grep -q -iE "$1" "./docker-log.log; then
-              printf "Could not find %s in %s\n" "$1" "./docker-log.log
+          check_for_config2() {
+            if ! grep -q -iE "$1" "./docker-log.log"; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./docker-log.log
+              printf "Found %s in %s\n" "$1" "./docker-log.log"
             fi
           }
           
