Fix build error;

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -6,6 +6,10 @@ on:
   pull_request:
     branches: [ main ]
 
+defaults:
+  run:
+    shell: bash
+
 jobs:
 
   build-and-run:
@@ -127,10 +131,16 @@ jobs:
       - name: Test - Server Configuration Applied
         run: |
           set -x
-          grep -q -iE "SaveWorldEveryMinutes=16" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "SteamPort1=25496" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "MaxPlayers=14" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "PauseEmpty=true" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "Open=false" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "PublicName=GitHub Action Test Server Name" "./ZomboidConfig/Server/GitHubActionTest.ini"
-          grep -q -iE "Password=github_action_test_password" "./ZomboidConfig/Server/GitHubActionTest.ini"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"; then
+              printf "Could not find %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
+            fi
+          }
+
+          check_for_config "SaveWorldEveryMinutes=16"
+          check_for_config "SteamPort1=25496"
+          check_for_config "MaxPlayers=14"
+          check_for_config "PauseEmpty=true"
+          check_for_config "Open=false"
+          check_for_config "PublicName=GitHub Action Test Server Name"
+          check_for_config "Password=github_action_test_password"
