Allow setting Map config in environment (#33)
* Allow setting Map config in environment

Signed-off-by: Jim O'Brien <jimmed@users.noreply.github.com>

* Update README.md

Co-authored-by: Renegade-Master <renegade.master.dev@protonmail.com>
Signed-off-by: Jim O'Brien <jimmed@users.noreply.github.com>

* Update src/run_server.sh

Co-authored-by: Renegade-Master <renegade.master.dev@protonmail.com>
Signed-off-by: Jim O'Brien <jimmed@users.noreply.github.com>

* Allow setting Map config in environment

Signed-off-by: Jim O'Brien <jimmed@users.noreply.github.com>

* Add map download;

- .github/workflows/docker-build.yml
  - Add Map Names and Mod IDs to all build environments.
  - Added checks to ensure that mod Map directories were created.

- README.md
  - Reformatting pass.
  - Add references to new MAP_NAMES environment variable.

- docker-compose.yaml
  - Added MAP_NAMES environment variable.

* Remove test.py

* Improve GHA Logging;

* Fix bug in docker-build.yaml;

* Correct GHA;

Signed-off-by: Jim O'Brien <jimmed@users.noreply.github.com>
Signed-off-by: Renegade-Master <renegade.master.dev@protonmail.com>
Co-authored-by: Renegade-Master <renegade.master.dev@protonmail.com>

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -84,14 +84,17 @@ jobs:
             --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
             --env=AUTOSAVE_INTERVAL="16" \
             --env=GAME_PORT="25496" \
+            --env=MAP_NAMES="BedfordFalls;North;South;West" \
             --env=MAX_PLAYERS="14" \
             --env=MAX_RAM="6144m" \
+            --env=MOD_NAMES="BedfordFalls" \
+            --env=MOD_WORKSHOP_IDS="522891356" \
             --env=PAUSE_ON_EMPTY="true" \
             --env=PUBLIC_SERVER="false" \
-            --env=SERVER_NAME="GitHubActionTest" \
-            --env=SERVER_PASSWORD="github_action_test_password" \
             --env=RCON_PASSWORD="github_action_test_rcon_password" \
             --env=RCON_PORT="27025" \
+            --env=SERVER_NAME="GitHubActionTest" \
+            --env=SERVER_PASSWORD="github_action_test_password" \
             docker.io/renegademaster/zomboid-dedicated-server:${{ steps.variables.outputs.datetime }} \
             2>&1 | tee ./docker-log.log
 
@@ -103,13 +106,18 @@ jobs:
         run: |
           sed -i "s/AUTOSAVE_INTERVAL=.*\"/AUTOSAVE_INTERVAL=16\"/g" "./docker-compose.yaml"
           sed -i "s/GAME_PORT=.*\"/GAME_PORT=25496\"/g" "./docker-compose.yaml"
+          sed -i "s/MAP_NAMES=.*\"/MAP_NAMES=BedfordFalls;North;South;West\"/g" "./docker-compose.yaml"
           sed -i "s/MAX_PLAYERS=.*\"/MAX_PLAYERS=14\"/g" "./docker-compose.yaml"
           sed -i "s/MAX_RAM=.*m\"/MAX_RAM=6144m\"/g" "./docker-compose.yaml"
+          sed -i "s/MOD_NAMES=.*\"/MOD_NAMES=BedfordFalls\"/g" "./docker-compose.yaml"
+          sed -i "s/MOD_WORKSHOP_IDS=.*\"/MOD_WORKSHOP_IDS=522891356\"/g" "./docker-compose.yaml"
           sed -i "s/PUBLIC_SERVER=.*/PUBLIC_SERVER=false\"/g" "./docker-compose.yaml"
-          sed -i "s/SERVER_NAME=.*/SERVER_NAME=GitHubActionTest\"/g" "./docker-compose.yaml"
-          sed -i "s/SERVER_PASSWORD=.*/SERVER_PASSWORD=github_action_test_password\"/g" "./docker-compose.yaml"
           sed -i "s/RCON_PASSWORD=.*/RCON_PASSWORD=github_action_test_rcon_password\"/g" "./docker-compose.yaml"
           sed -i "s/RCON_PORT=.*\"/RCON_PORT=27025\"/g" "./docker-compose.yaml"
+          sed -i "s/SERVER_NAME=.*/SERVER_NAME=GitHubActionTest\"/g" "./docker-compose.yaml"
+          sed -i "s/SERVER_PASSWORD=.*/SERVER_PASSWORD=github_action_test_password\"/g" "./docker-compose.yaml"
+
+          cat docker-compose.yaml
 
       - name: Build the Docker-Compose Image
         if: ${{ success() && matrix.system == 'docker-compose' }}
@@ -159,29 +167,31 @@ jobs:
             --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
             --env=AUTOSAVE_INTERVAL="16" \
             --env=GAME_PORT="25496" \
+            --env=MAP_NAMES="BedfordFalls;North;South;West" \
             --env=MAX_PLAYERS="14" \
             --env=MAX_RAM="6144m" \
+            --env=MOD_NAMES="BedfordFalls" \
+            --env=MOD_WORKSHOP_IDS="522891356" \
             --env=PAUSE_ON_EMPTY="true" \
             --env=PUBLIC_SERVER="false" \
-            --env=SERVER_NAME="GitHubActionTest" \
-            --env=SERVER_PASSWORD="github_action_test_password" \
             --env=RCON_PASSWORD="github_action_test_rcon_password" \
             --env=RCON_PORT="27025" \
+            --env=SERVER_NAME="GitHubActionTest" \
+            --env=SERVER_PASSWORD="github_action_test_password" \
             docker.io/renegademaster/zomboid-dedicated-server:${{ steps.variables.outputs.datetime }} \
             2>&1 | tee ./docker-log.log
 
-      - name: Investigate File Structure on Failure
-        if: ${{ failure() }}
+      - name: Investigate File Structure
         run: |
           pwd
           echo ''
-          ls -lAuhFn ./ZomboidDedicatedServer/
+          ls -lAuhFn ./ZomboidDedicatedServer/ > ./dedicated-server-install-listing.txt
           echo ''
-          ls -lAuhFn ./ZomboidConfig/
+          ls -lAuhFn ./ZomboidConfig/ > ./dedicated-server-config-listing.txt
           echo ''
-          tree -aL 4 ./ZomboidDedicatedServer/
+          tree -aL 10 ./ZomboidDedicatedServer/ > ./dedicated-server-install-tree.txt
           echo ''
-          tree -aL 4 ./ZomboidConfig/
+          tree -aL 10 ./ZomboidConfig/ > ./dedicated-server-config-tree.txt
 
       - name: Upload Docker Logs
         if: ${{ always() }}
@@ -197,9 +207,14 @@ jobs:
         with:
           name: server-configs-${{ matrix.system }}
           path: |
+            docker-compose.yaml
             ZomboidConfig/Server/GitHubActionTest.ini
             ZomboidConfig/Server/GitHubActionTest_SandboxVars.lua
             ZomboidDedicatedServer/ProjectZomboid64.json
+            dedicated-server-install-listing.txt
+            dedicated-server-config-listing.txt
+            dedicated-server-install-tree.txt
+            dedicated-server-config-tree.txt
 
   test-docker:
     name: Test Server
@@ -227,10 +242,10 @@ jobs:
         run: |
           check_for_config() {
             if ! grep -q -iE "$1" "./docker-log.log"; then
-              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+              printf "Could not find [%s] in [%s]\n" "$1" "./docker-log.log"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./docker-log.log"
+              printf "Found [%s] in [%s]\n" "$1" "./docker-log.log"
             fi
           }
 
@@ -240,10 +255,10 @@ jobs:
         run: |
           check_for_config() {
             if ! grep -q -iE "$1" "./docker-log.log"; then
-              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+              printf "Could not find [%s] in [%s]\n" "$1" "./docker-log.log"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./docker-log.log"
+              printf "Found [%s] in [%s]\n" "$1" "./docker-log.log"
             fi
           }
 
@@ -253,9 +268,9 @@ jobs:
         run: |
           check_for_config() {
             if ! grep -q -iE "$1" "./docker-log.log"; then
-              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+              printf "Could not find [%s] in [%s]\n" "$1" "./docker-log.log"
             else
-              printf "Found %s in %s\n" "$1" "./docker-log.log"
+              printf "Found [%s] in [%s]\n" "$1" "./docker-log.log"
               exit 1
             fi
           }
@@ -267,10 +282,10 @@ jobs:
         run: |
           check_for_config() {
             if ! grep -q -iE "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"; then
-              printf "Could not find %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+              printf "Could not find [%s] in [%s]\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+              printf "Found [%s] in [%s]\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
             fi
           }
 
@@ -278,21 +293,63 @@ jobs:
 
       - name: Test - Server Configuration Applied
         run: |
+          install_directory="./ZomboidDedicatedServer"
+          workshop_directory="${install_directory}/steamapps/workshop"
+          mods_directory="${workshop_directory}/content/108600/522891356/mods"
+          bedford_maps="${mods_directory}/Bedford Falls/media/maps"
+
+          map_search_string="$(cat << EOF
+          │       ├── content
+          │       │   └── 108600
+          │       │       └── 522891356
+          │       │           └── mods
+          │       │               └── Bedford Falls
+          │       │                   ├── media
+          │       │                   │   ├── lua
+          │       │                   │   │   ├── client
+          EOF
+          )"
+
+          py_script="$(cat << EOF
+          to_find = """${map_search_string}"""
+
+          with open("dedicated-server-install-tree.txt", "r") as file:
+              file_string = file.read()
+
+              if (to_find in file_string):
+                  print("FOUND")
+              else:
+                  print("NOT_FOUND")
+          EOF
+          )"
+
           check_for_config() {
             if ! grep -q -iE "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"; then
-              printf "Could not find %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
+              printf "Could not find [%s] in [%s]\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
+              printf "Found [%s] in [%s]\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
             fi
           }
 
-          check_for_config "SaveWorldEveryMinutes=16"
-          check_for_config "SteamPort1=25496"
+          check_for_directory() {
+            if [[ $(python3 -c "${py_script}") == "FOUND" ]]; then
+              printf "Found map directory in [%s]\n" "${bedford_maps}"
+            else
+              printf "Could not find map directory in [%s]\n" "${bedford_maps}"
+              exit 1
+            fi
+          }
+
+          check_for_config "Map=BedfordFalls;North;South;West"
           check_for_config "MaxPlayers=14"
-          check_for_config "PauseEmpty=true"
           check_for_config "Open=false"
-          check_for_config "PublicName=GitHubActionTest"
           check_for_config "Password=github_action_test_password"
+          check_for_config "PauseEmpty=true"
+          check_for_config "PublicName=GitHubActionTest"
           check_for_config "RCONPassword=github_action_test_rcon_password"
           check_for_config "RCONPort=27025"
+          check_for_config "SaveWorldEveryMinutes=16"
+          check_for_config "SteamPort1=25496"
+
+          check_for_directory
