Modify build test; SHOULD FAIL;

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -115,15 +115,42 @@ jobs:
 
       - name: Test - Server Started
         run: |
-          grep -q -iE "LuaNet: Initialization \[DONE\]" "./docker-log.log"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./docker-log.log; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./docker-log.log
+            fi
+          }
+          
+          check_for_config "LuaNet: Initialization \[DONE\]"
 
       - name: Test - Sed Command Completed
         run: |
-          ! grep -q -iE "sed: can't read" "./docker-log.log"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./docker-log.log"; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+            else
+              printf "Found %s in %s\n" "$1" "./docker-log.log"
+              exit 1
+            fi
+          }
+          
+          check_for_config "sed: can't read"
 
       - name: Test - Server JVM Configuration Applied
         run: |
-          grep -q -iE "\-Xmx6144m" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"; then
+              printf "Could not find %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+            fi
+          }
+          
+          check_for_config "\-Xmx6144m"
 
       - name: Test - Server Configuration Applied
         run: |
@@ -131,6 +158,8 @@ jobs:
             if ! grep -q -iE "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"; then
               printf "Could not find %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
               exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
             fi
           }
 
@@ -140,4 +169,4 @@ jobs:
           check_for_config "PauseEmpty=true"
           check_for_config "Open=false"
           check_for_config "PublicName=GitHubActionTest"
-          check_for_config "Password=github_action_test_password"
+          check_for_config "Password=github_action_test_passwords"
