Add Issue Templates; Clean variables; (#9)
* Add Issue Templates; Clean variables; Improve build;

- .github/ISSUE_TEMPLATE/
  - Created Issue templates for Issues and Feature Requests.

- .github/workflows/docker-build.yml
  - Added more configuration options to test run to verify that configurations are setting properly.
  - Added Bash as the default Shell.
  - Improved readability of failed logs by printing what is being checked.

- README.md
  - Moved the Optional Arguments table closer to the start of the document.
  - Removed the second repeated Optional Arguments table.
  - Removed references to Environment Variables that are no longer configurable from Docker.
    - To configure these parameters, you can edit the files locally after initial installation.
  - Changed the ordering of the displayed environment variables to make them easier to read through.

- docker-compose.yaml
  - Removed references to Environment Variables that are no longer configured from Docker.
  - Changed the ordering of the displayed environment variables to make them easier to read through.

- src/run_server.sh
  - Removed references to Environment Variables that are no longer configured from Docker.
  - Changed the ordering of the displayed environment variables to make them easier to read through.

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -6,6 +6,10 @@ on:
   pull_request:
     branches: [ main ]
 
+defaults:
+  run:
+    shell: bash
+
 jobs:
 
   build-and-run:
@@ -51,6 +55,14 @@ jobs:
           --user ${{ steps.variables.outputs.userid }}:${{ steps.variables.outputs.groupid }} \
           --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer \
           --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
+          --env=AUTOSAVE_INTERVAL="16" \
+          --env=GAME_PORT="25496" \
+          --env=MAX_PLAYERS="14" \
+          --env=MAX_RAM="6144m" \
+          --env=PAUSE_ON_EMPTY="true" \
+          --env=PUBLIC_SERVER="false" \
+          --env=SERVER_NAME="GitHubActionTest" \
+          --env=SERVER_PASSWORD="github_action_test_password" \
           renegademaster/zomboid-dedicated-server:${{ steps.variables.outputs.datetime }} \
           2>&1 | tee ./docker-log.log
 
@@ -81,8 +93,8 @@ jobs:
         with:
           name: server-configs
           path: |
-            ZomboidConfig/Server/ZomboidServer.ini
-            ZomboidConfig/Server/ZomboidServer_SandboxVars.lua
+            ZomboidConfig/Server/GitHubActionTest.ini
+            ZomboidConfig/Server/GitHubActionTest_SandboxVars.lua
             ZomboidDedicatedServer/ProjectZomboid64.json
 
   test:
@@ -103,20 +115,58 @@ jobs:
 
       - name: Test - Server Started
         run: |
-          grep -q -iE "LuaNet: Initialization \[DONE\]" "./docker-log.log"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./docker-log.log"; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./docker-log.log"
+            fi
+          }
+          
+          check_for_config "LuaNet: Initialization \[DONE\]"
 
       - name: Test - Sed Command Completed
         run: |
-          ! grep -q -iE "sed: can't read" "./docker-log.log"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./docker-log.log"; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+            else
+              printf "Found %s in %s\n" "$1" "./docker-log.log"
+              exit 1
+            fi
+          }
+          
+          check_for_config "sed: can't read"
 
       - name: Test - Server JVM Configuration Applied
         run: |
-          grep -q -iE "\-Xmx4096m" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"; then
+              printf "Could not find %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./ZomboidDedicatedServer/ProjectZomboid64.json"
+            fi
+          }
+          
+          check_for_config "\-Xmx6144m"
 
       - name: Test - Server Configuration Applied
         run: |
-          grep -q -iE "Open=true" "./ZomboidConfig/Server/ZomboidServer.ini"
+          check_for_config() {
+            if ! grep -q -iE "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"; then
+              printf "Could not find %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./ZomboidConfig/Server/GitHubActionTest.ini"
+            fi
+          }
 
-      - name: Test - Server Game Rules Configuration Applied
-        run: |
-          grep -q -iE "CarSpawnRate = 3" "./ZomboidConfig/Server/ZomboidServer_SandboxVars.lua"
+          check_for_config "SaveWorldEveryMinutes=16"
+          check_for_config "SteamPort1=25496"
+          check_for_config "MaxPlayers=14"
+          check_for_config "PauseEmpty=true"
+          check_for_config "Open=false"
+          check_for_config "PublicName=GitHubActionTest"
+          check_for_config "Password=github_action_test_password"
